# Generated by Django 4.0 on 2022-03-12 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('books', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rateofbook',
            unique_together={('book', 'user')},
        ),
    ]
