# Generated by Django 4.0 on 2022-03-12 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='on_sale',
        ),
    ]
